-- Database Translation Script
-- This script updates all localized columns with French and English translations.

-- Association Info
UPDATE public.association_info SET name_fr = 'Association Essaouira Darna', name_en = 'Essaouira Darna Association', tagline_fr = 'Prise en charge, hébergement et intégration des enfants en situation difficile dans la province d''Essaouira', tagline_en = 'Care, housing, and integration of children in difficult situations in the Essaouira province', description_fr = 'L''association Essaouira Darna a été fondée dans le but de fournir des soins complets, une éducation et un soutien psychosocial aux enfants orphelins, abandonnés ou vivant dans des conditions sociales difficiles dans la ville d''Essaouira et ses environs.', description_en = 'The Essaouira Darna Association was founded with the aim of providing comprehensive care, education, and psychosocial support to orphaned, abandoned children or those living in difficult social conditions in the city of Essaouira and its surroundings.', address_fr = 'Lotissement El Ghazoua, Essaouira, Maroc', address_en = 'El Ghazoua Subdivision, Essaouira, Morocco' WHERE id = 'd5983249-b21d-49e9-a5c3-d43d7e316848';

-- Nav Links
UPDATE public.nav_links SET label_fr = 'Accueil', label_en = 'Home' WHERE id = '83de1a04-9789-4416-9f5f-0cef3e89b872';
UPDATE public.nav_links SET label_fr = 'À propos', label_en = 'About Us' WHERE id = '150df4a3-ace1-40b4-bd40-a28f8d932eb6';
UPDATE public.nav_links SET label_fr = 'Nos Projets', label_en = 'Our Projects' WHERE id = '7beb3eaf-4312-4b7f-b3eb-ec8009750123';
UPDATE public.nav_links SET label_fr = 'Comment Contribuer', label_en = 'How to Contribute' WHERE id = 'fbf78ce5-ca5d-4dfa-b037-d47a6d21d469';
UPDATE public.nav_links SET label_fr = 'Contactez-nous', label_en = 'Contact Us' WHERE id = '06270d3a-08dd-4917-b9e7-42782d354e9e';

-- Stats
UPDATE public.stats SET label_fr = 'Bénéficiaire', label_en = 'Beneficiary', description_fr = 'Nombre de bénéficiaires jusqu''au 31/12/2025', description_en = 'Number of beneficiaries up to 31/12/2025' WHERE id = '19e23818-7415-4d9f-b2be-1259052c7bfb';
UPDATE public.stats SET label_fr = 'MAD', label_en = 'MAD', description_fr = 'Montant estimé des dons caritatifs pour 2026 (24%)', description_en = 'Estimated amount of charitable donations for 2026 (24%)' WHERE id = '2a24b3be-5f5c-4c80-b1bc-f21b51b477e8';
UPDATE public.stats SET label_fr = 'MAD', label_en = 'MAD', description_fr = 'Budget de fonctionnement estimé pour 2026', description_en = 'Estimated operating budget for 2026' WHERE id = 'b6b01290-1518-4703-8409-df719b87b121';
UPDATE public.stats SET label_fr = 'Bénéficiaire', label_en = 'Beneficiary', description_fr = 'Nombre de bénéficiaires pour 2026', description_en = 'Number of beneficiaries for 2026' WHERE id = '9b378ddf-0470-4997-85e0-266369f422a0';
UPDATE public.stats SET label_fr = 'Bénéficiaire', label_en = 'Beneficiary', description_fr = 'Nombre de bénéficiaires jusqu''au 31/12/2025', description_en = 'Number of beneficiaries up to 31/12/2025' WHERE id = 'b7c39582-6f57-4ec0-9fdd-8979fc85f6da';
UPDATE public.stats SET label_fr = 'Bénéficiaire', label_en = 'Beneficiary', description_fr = 'Nombre de bénéficiaires pour 2026', description_en = 'Number of beneficiaries for 2026' WHERE id = '6b023416-5a5f-4cb1-9ae3-d1535e947765';
UPDATE public.stats SET label_fr = 'MAD', label_en = 'MAD', description_fr = 'Montant estimé des dons caritatifs pour 2026 (24%)', description_en = 'Estimated amount of charitable donations for 2026 (24%)' WHERE id = '3394dd85-0a11-4d0e-bfd6-aa8fac20e587';
UPDATE public.stats SET label_fr = 'MAD', label_en = 'MAD', description_fr = 'Budget de fonctionnement estimé pour 2026', description_en = 'Estimated operating budget for 2026' WHERE id = 'f2a7ca45-f776-41c1-bcaa-42e189a9d38a';

-- Association Values
UPDATE public.association_values SET title_fr = 'Qualité des Services', title_en = 'Quality of Services', description_fr = 'Nos services sont gratuits pour garantir leur continuité et leur conformité à la loi 14/05', description_en = 'Our services are free to ensure their continuity and compliance with Law 14/05' WHERE id = '7269bc49-ba46-419c-8dc6-e263718d9a59';
UPDATE public.association_values SET title_fr = 'Partenariat', title_en = 'Partnership', description_fr = 'Nous sommes convaincus que le succès de toute action sociale repose sur la participation et la coopération entre les individus', description_en = 'We are convinced that the success of any social action relies on participation and cooperation between individuals' WHERE id = '76e41a06-d3e2-4054-951a-7322fc352401';
UPDATE public.association_values SET title_fr = 'Crédibilité', title_en = 'Credibility', description_fr = 'Dans toutes les initiatives qui nous aident à fournir l''assistance nécessaire aux enfants dans le besoin', description_en = 'In all initiatives that help us provide necessary assistance to children in need' WHERE id = 'bbd2e5f1-e37f-460c-ba29-537fa3dcbc56';
UPDATE public.association_values SET title_fr = 'Communication', title_en = 'Communication', description_fr = 'En communication constante avec nos partenaires', description_en = 'In constant communication with our partners' WHERE id = '35a1ed92-474c-416c-a47b-903d74009ba0';
UPDATE public.association_values SET title_fr = 'Solidarité', title_en = 'Solidarity', description_fr = 'Entre les bénéficiaires et le personnel de l''association', description_en = 'Between beneficiaries and association staff' WHERE id = 'f1e49b0c-5056-412f-a5f9-df94e9e8a25b';
UPDATE public.association_values SET title_fr = 'Transparence', title_en = 'Transparency', description_fr = 'Dans la gestion des affaires administratives et financières', description_en = 'In the management of administrative and financial affairs' WHERE id = '22043096-79b7-4a34-b11b-290213cae15a';
UPDATE public.association_values SET title_fr = 'Prise en Charge Globale', title_en = 'Comprehensive Care', description_fr = 'Fournir un abri, de la nourriture, des vêtements et des soins médicaux à chaque enfant résidant au foyer pour assurer sa croissance équilibrée et naturelle.', description_en = 'Providing shelter, food, clothing, and medical care to every child residing in the home to ensure their balanced and natural growth.' WHERE id = '3fac07dd-7f8d-4404-9fc0-56502e2e433b';
UPDATE public.association_values SET title_fr = 'Éducation et Orientation', title_en = 'Education and Guidance', description_fr = 'Suivre les enfants dans leur parcours éducatif, les guider et les qualifier pour entrer sur le marché du travail et devenir autonomes.', description_en = 'Following children in their educational paths, guiding them, and qualifying them to enter the job market and become self-reliant.' WHERE id = '356eb11d-6127-4526-a98e-add82b9a0edd';
UPDATE public.association_values SET title_fr = 'Transparence et Engagement', title_en = 'Transparency and Commitment', description_fr = 'Engagement envers les normes les plus élevées de gouvernance financière et de gestion administrative avec tous les partenaires, donateurs et institutions.', description_en = 'Commitment to the highest standards of financial governance and administrative management with all partners, donors, and institutions.' WHERE id = '0b23303d-9b0b-40a7-bdfb-a4b3d70c94b6';


-- About Content
UPDATE public.about_content SET title_fr = NULL, title_en = NULL, content_fr = 'L''association Essaouira Darna est une institution de protection sociale qui s''occupe des enfants abandonnés ou en situation difficile.', content_en = 'The Essaouira Darna Association is a social protection institution that cares for abandoned children or those in difficult situations.' WHERE id = 'ecdb2447-c66b-4b69-b5f9-1bceca21e202';
UPDATE public.about_content SET title_fr = NULL, title_en = NULL, content_fr = 'L''association a été fondée le 21 mars 2008 grâce à l''Initiative Nationale pour le Développement Humain lancée en 2005 à Essaouira.', content_en = 'The association was founded on March 21, 2008, thanks to the National Initiative for Human Development launched in 2005 in Essaouira.' WHERE id = '71c3ee57-5d2b-4cb2-a426-a6c77a97731f';
UPDATE public.about_content SET title_fr = NULL, title_en = NULL, content_fr = 'L''institution a été légalement autorisée en avril 2009, conformément à la décision n° 10/09 du Ministère de la Solidarité, de la Femme, de la Famille et du Développement Social, avec une capacité de 120 bénéficiaires.', content_en = 'The institution was legally authorized in April 2009, in accordance with Decision No. 10/09 of the Ministry of Solidarity, Women, Family and Social Development, with a capacity of 120 beneficiaries.' WHERE id = '552d72a4-df54-457f-a92b-3ebfd2040f43';
UPDATE public.about_content SET title_fr = NULL, title_en = NULL, content_fr = 'La gestion de l''institution est soumise à la loi n° 14-05 relative aux conditions d''ouverture et de gestion des établissements de protection sociale au Maroc.', content_en = 'The management of the institution is subject to Law No. 14-05 regarding the conditions for opening and managing social protection establishments in Morocco.' WHERE id = 'e7b57b74-9ee2-4808-b9ea-a526243626b5';
UPDATE public.about_content SET title_fr = 'Un avenir sans enfants en situation de rue', title_en = 'A future without street children', content_fr = 'À l''association Essaouira Darna, nous aspirons à ce que la province d''Essaouira soit totalement exempte du phénomène des enfants sans-abri ou en danger, et nous voulons garantir à chaque enfant de cette catégorie un abri digne et une chance égale pour une éducation de qualité et un développement sain.', content_en = 'At the Essaouira Darna Association, we aspire for the Essaouira province to be completely free of the phenomenon of homeless or at-risk children, and we want to guarantee every child in this category a dignified shelter and an equal chance for quality education and healthy development.' WHERE id = '24cd0445-70a4-4235-b994-921e95cb5492';
UPDATE public.about_content SET title_fr = 'Prise en charge, hébergement et intégration sociale', title_en = 'Care, housing, and social integration', content_fr = 'Notre mission est d''accueillir les enfants orphelins, abandonnés ou vivant dans une situation difficile, de leur fournir un abri sûr, une alimentation complète, des soins médicaux, une éducation et des activités récréatives, afin de préparer leur intégration effective dans leur environnement social et professionnel en tant que membres actifs et indépendants.', content_en = 'Our mission is to welcome orphaned, abandoned, or children living in difficult situations, to provide them with a safe shelter, comprehensive nutrition, medical care, education, and recreational activities, in order to prepare their effective integration into their social and professional environment as active and independent members.' WHERE id = 'b8033d4c-6aa1-4006-b0c8-df4c4037cd7a';

-- History Timeline
UPDATE public.history_timeline SET description_fr = 'En partenariat avec la préfecture d''Essaouira, le projet « Essaouira Darna » est né dans le cadre de l''INDH (Initiative Nationale pour le Développement Humain).', description_en = 'In partnership with the Essaouira prefecture, the ''Essaouira Darna'' project was born within the framework of the INDH (National Initiative for Human Development).' WHERE id = '09589337-3a40-4763-b199-2ba03376d4d1';
UPDATE public.history_timeline SET description_fr = 'L''association a officiellement ouvert ses portes et a commencé à accueillir des enfants abandonnés et ceux confrontés à des situations sociales difficiles, venant principalement d''autres associations comme l''Association Annajma et l''Association Nour Mogador.', description_en = 'The association officially opened its doors and began welcoming abandoned children and those facing difficult social situations, coming mainly from other associations such as the Annajma Association and the Nour Mogador Association.' WHERE id = '0d59a7c9-2e75-4930-a9a4-20e6a6da458c';
UPDATE public.history_timeline SET description_fr = 'L''institution a obtenu une autorisation légale conformément à la loi 14-05 et à la décision n° 10/09 du Ministère de la Solidarité, de la Femme et du Développement Social, avec une capacité de 60 bénéficiaires.', description_en = 'The institution obtained legal authorization in accordance with Law 14-05 and Decision No. 10/09 from the Ministry of Solidarity, Women, and Social Development, with a capacity of 60 beneficiaries.' WHERE id = '85100536-79af-4206-b4fb-d12989f6fc4d';
UPDATE public.history_timeline SET description_fr = 'L''institution a été autorisée, conformément à la loi 14-05, à augmenter sa capacité d''accueil à 120 bénéficiaires.', description_en = 'The institution was authorized, in accordance with Law 14-05, to increase its hosting capacity to 120 beneficiaries.' WHERE id = '6df6325b-841a-4f3d-8b9f-260b315c9e3a';
UPDATE public.history_timeline SET description_fr = 'L''institution est actuellement gérée par une association composée de sept membres, dont trois femmes.', description_en = 'The institution is currently managed by an association composed of seven members, including three women.' WHERE id = '2fa66d0e-d132-4b7f-a605-20096075c0f4';

-- Projects
UPDATE public.projects SET title_fr = 'Équipement et gestion de l''orphelinat Darna', title_en = 'Equipping and running the Darna orphanage', short_description_fr = 'Fournir un abri sûr et des soins complets aux enfants orphelins et en situation de rue à Essaouira.', short_description_en = 'Providing a safe shelter and comprehensive care for orphaned and street children in Essaouira.', long_description_fr = 'Ce projet continu vise à couvrir les coûts opérationnels du centre de soins à Essaouira (Darna), y compris l''alimentation, l''habillement, les soins médicaux et l''éducation pour les enfants résidents. Nous nous efforçons de fournir un environnement familial chaleureux qui soutient leur développement intégré et leur intégration dans la société.', long_description_en = 'This ongoing project aims to cover the operational costs of the care center in Essaouira (Darna), including nutrition, clothing, medical care, and education for the resident children. We strive to provide a warm family environment that supports their integrated development and integration into society.' WHERE id = 'da94ef41-4565-4fde-b6b6-de79bdabb8fc';
UPDATE public.projects SET title_fr = 'الرعاية الصحية والدعم الغذائي للأسر المعوزة', title_en = 'الرعاية الصحية والدعم الغذائي للأسر المعوزة', short_description_fr = 'تقديم المساعدات الغذائية الأساسية والرعاية الصحية الدورية للأسر الأكثر هشاشة.', short_description_en = 'تقديم المساعدات الغذائية الأساسية والرعاية الصحية الدورية للأسر الأكثر هشاشة.', long_description_fr = 'يركز هذا البرنامج على الفحوصات الطبية الدورية والتكفل بمصاريف الأدوية والعمليات الجراحية المستعجلة لفائدة الأطفال المستفيدين وأمهاتهم اللواتي يعشن في ظروف قاسية، إلى جانب توزيع قفف غذائية دورية.', long_description_en = 'يركز هذا البرنامج على الفحوصات الطبية الدورية والتكفل بمصاريف الأدوية والعمليات الجراحية المستعجلة لفائدة الأطفال المستفيدين وأمهاتهم اللواتي يعشن في ظروف قاسية، إلى جانب توزيع قفف غذائية دورية.' WHERE id = '879e3be8-cf5f-47c9-b1b3-011af93ebad1';
UPDATE public.projects SET title_fr = 'دعم التعليم الأولي والدمج المدرسي', title_en = 'دعم التعليم الأولي والدمج المدرسي', short_description_fr = 'تمويل الرسوم المدرسية واقتناء المحافظ والكتب المدرسية للأطفال المعوزين.', short_description_en = 'تمويل الرسوم المدرسية واقتناء المحافظ والكتب المدرسية للأطفال المعوزين.', long_description_fr = 'نسعى لضمان عدم انقطاع أي طفل عن الدراسة بسبب الصعوبات المادية. يشمل هذا المشروع شراء الكتب المدرسية، المحافظ، الدفاتر، والأدوات التعليمية، بالإضافة إلى توفير حصص الدعم والتقوية ودروس الدعم النفسي-التربوي للأطفال.', long_description_en = 'نسعى لضمان عدم انقطاع أي طفل عن الدراسة بسبب الصعوبات المادية. يشمل هذا المشروع شراء الكتب المدرسية، المحافظ، الدفاتر، والأدوات التعليمية، بالإضافة إلى توفير حصص الدعم والتقوية ودروس الدعم النفسي-التربوي للأطفال.' WHERE id = '9fb9674d-9684-4b74-b413-3e9a15e4d244';

-- Project Supplies
UPDATE public.project_supplies SET name_fr = 'سرير خشبي مريح للأطفال', name_en = 'سرير خشبي مريح للأطفال' WHERE id = '3e06a832-3946-4316-8e31-de84910758a7';
UPDATE public.project_supplies SET name_fr = 'غطاء صوفي شتوي دافئ', name_en = 'غطاء صوفي شتوي دافئ' WHERE id = 'a6cd74eb-2284-494e-ac5c-aec03fb41372';
UPDATE public.project_supplies SET name_fr = 'مجموعة خزانة ملابس شخصية لكل طفل', name_en = 'مجموعة خزانة ملابس شخصية لكل طفل' WHERE id = '7f220c4d-584e-461c-aa84-19be7cc040e4';
UPDATE public.project_supplies SET name_fr = 'حقيبة طبية للإسعافات الأولية', name_en = 'حقيبة طبية للإسعافات الأولية' WHERE id = '2593076d-c565-4e55-9c7d-e732f5167e04';
UPDATE public.project_supplies SET name_fr = 'جهاز تدفئة آمن للغرف المشتركة', name_en = 'جهاز تدفئة آمن للغرف المشتركة' WHERE id = '034bc6cd-59f4-4df5-99b6-d94d32c68ad8';
UPDATE public.project_supplies SET name_fr = 'وجبة غذائية متكاملة لطفل لمدة شهر', name_en = 'وجبة غذائية متكاملة لطفل لمدة شهر' WHERE id = '2daee1e3-c6c0-4472-ab33-5c4125dc9bdd';
UPDATE public.project_supplies SET name_fr = 'طاولة دراسية ثنائية للقسم', name_en = 'طاولة دراسية ثنائية للقسم' WHERE id = '28968139-7de3-4369-bfd5-e14f22d7ea69';
UPDATE public.project_supplies SET name_fr = 'حاسوب محمول للتعليم والتوجيه التفاعلي', name_en = 'حاسوب محمول للتعليم والتوجيه التفاعلي' WHERE id = '1c115d98-b853-4c6c-9733-6fbcd763df60';
UPDATE public.project_supplies SET name_fr = 'لوحة جدارية تفاعلية للتدريس', name_en = 'لوحة جدارية تفاعلية للتدريس' WHERE id = '12deecab-0cf5-4c92-acd0-de1ebcd9b425';
UPDATE public.project_supplies SET name_fr = 'Panier de denrées de base pour une famille pendant un mois', name_en = 'Basic food basket for a family for a month' WHERE id = '7f4c38e0-27eb-4669-af9b-2d8658efa43a';
UPDATE public.project_supplies SET name_fr = 'Fourniture de médicaments de base et d''ordonnances urgentes', name_en = 'Providing basic medicines and urgent prescriptions' WHERE id = '1d7071dd-d5e4-4c3d-a8f5-935141c396ad';
UPDATE public.project_supplies SET name_fr = 'Lunettes correctrices pour les enfants malvoyants', name_en = 'Corrective glasses for visually impaired children' WHERE id = 'ebd0a592-b1c9-46b0-a59f-ceb9ab31062c';
UPDATE public.project_supplies SET name_fr = 'Cartable entièrement équipé avec cahiers et stylos', name_en = 'Fully equipped school bag with notebooks and pens' WHERE id = '794bb868-cbcf-4961-a3e0-de4a5146be2f';
UPDATE public.project_supplies SET name_fr = 'Livres et manuels de niveau primaire', name_en = 'Primary school books and textbooks' WHERE id = 'db45efb1-cd2f-4122-b112-83c8bfd3fa98';


-- Members
UPDATE public.members SET name_fr = 'Khaled BENGHADA', name_en = 'Khaled BENGHADA', role_fr = 'Président fondateur', role_en = 'Founding President' WHERE id = 'ecdc2ae6-d614-404c-b95c-0d9b045ff31a';
UPDATE public.members SET name_fr = 'Aziz ECHCHAIBI SEFRIOUI', name_en = 'Aziz ECHCHAIBI SEFRIOUI', role_fr = 'Président', role_en = 'President' WHERE id = '0be63235-b7e9-4963-b244-adab7b2eef98';
UPDATE public.members SET name_fr = 'Zahra KENABO', name_en = 'Zahra KENABO', role_fr = 'Président adjoint', role_en = 'Vice President' WHERE id = '07a5e5d1-36c2-4d09-954a-1478c3b2129c';
UPDATE public.members SET name_fr = 'Souad BAINO', name_en = 'Souad BAINO', role_fr = 'Trésorier', role_en = 'Treasurer' WHERE id = '2aa5bb6e-b63e-48de-8fea-f1a467ee4346';
UPDATE public.members SET name_fr = 'Habib EL BAHI', name_en = 'Habib EL BAHI', role_fr = 'Trésorier adjoint', role_en = 'Deputy Treasurer' WHERE id = '9efc6797-ced4-4a54-b075-bf813a882ea5';
UPDATE public.members SET name_fr = 'Aicha LACHAB', name_en = 'Aicha LACHAB', role_fr = 'Secrétaire Général', role_en = 'General Secretary' WHERE id = 'a7c8855b-69a3-40f0-a60a-a234f0220eb0';
UPDATE public.members SET name_fr = 'Noura SARAOUI', name_en = 'Noura SARAOUI', role_fr = 'Secrétaire adjoint', role_en = 'Deputy Secretary' WHERE id = '0562db62-07a9-4e7e-90d2-9b331db08b21';
UPDATE public.members SET name_fr = 'Michel Bohbot', name_en = 'Michel Bohbot', role_fr = 'Expert en art contemporain', role_en = 'Contemporary Art Expert' WHERE id = '3c25e418-25ab-41a7-9ec2-00fa5e51930d';
UPDATE public.members SET name_fr = 'Fatimzahra EL Hour', name_en = 'Fatimzahra EL Hour', role_fr = 'Miss Maroc année 2015', role_en = 'Miss Morocco 2015' WHERE id = '2cd95f6c-0365-4ad2-8220-97e46046c770';
UPDATE public.members SET name_fr = 'Professeur Abdelhafid LAHLAIDI', name_en = 'Professeur Abdelhafid LAHLAIDI', role_fr = 'Médecin chirurgien cardio vasculaire chercheur génie d''anatomie', role_en = 'Médecin chirurgien cardio vasculaire chercheur génie d''anatomie' WHERE id = 'cdc3e41c-5fdf-49be-b59f-e6a121b60f8d';
UPDATE public.members SET name_fr = 'Mourad BOURIKI', name_en = 'Mourad BOURIKI', role_fr = 'Gagnant de la 1ère Saison "The Voice أحلى صوت"', role_en = 'Gagnant de la 1ère Saison "The Voice أحلى صوت"' WHERE id = '1877a47c-4380-474d-ad0c-fc84180d2ac9';
UPDATE public.members SET name_fr = 'Bouchra BOUJLIL', name_en = 'Bouchra BOUJLIL', role_fr = 'Directrice', role_en = 'Directrice' WHERE id = 'bd0d63fd-55b5-4740-a9e6-8d09e5ff665e';
UPDATE public.members SET name_fr = 'Saida DAROUI', name_en = 'Saida DAROUI', role_fr = 'Surveillante générale', role_en = 'Surveillante générale' WHERE id = 'c9b7ebb4-b905-4833-a88b-fc87bfe3727a';
UPDATE public.members SET name_fr = 'Rabiaa ZETOUNE', name_en = 'Rabiaa ZETOUNE', role_fr = 'Coordinatrice éducatrices', role_en = 'Coordinatrice éducatrices' WHERE id = '7721deb1-4f4e-4598-9074-3e86a36b59bc';
UPDATE public.members SET name_fr = 'Fatimzzahra ADI', name_en = 'Fatimzzahra ADI', role_fr = 'Responsable Financière', role_en = 'Responsable Financière' WHERE id = 'dbc234e3-80c9-4c98-8857-1f430f4efde9';

-- Partners
UPDATE public.partners SET name_fr = 'Groupe Accor Hôtel Ibis Essaouira', name_en = 'Groupe Accor Hôtel Ibis Essaouira' WHERE id = '6e2fbf9f-f525-4985-a332-5f95b0996da2';
UPDATE public.partners SET name_fr = 'Hôtels prestige Marrakech', name_en = 'Hôtels prestige Marrakech' WHERE id = '97c8d0b4-fe39-40e4-bbc8-a4389e8bce6e';
UPDATE public.partners SET name_fr = 'Laboratoire Galinica Casablanca pharmacie', name_en = 'Laboratoire Galinica Casablanca pharmacie' WHERE id = '41fbb177-9d25-4d3f-bee0-81ff33903f30';
UPDATE public.partners SET name_fr = 'Laboratoire Abdelkarim EL KHATABI d''Essaouira', name_en = 'Laboratoire Abdelkarim EL KHATABI d''Essaouira' WHERE id = '0ebe9279-a4e4-4057-9ce7-1d406a443e2c';
UPDATE public.partners SET name_fr = 'Comité Provincial de Développement Humain de la Province d''Essaouira', name_en = 'Comité Provincial de Développement Humain de la Province d''Essaouira' WHERE id = '0698efac-6328-473a-8e92-2b9a8f4577c3';
UPDATE public.partners SET name_fr = 'Ministère de la famille solidarité égalité et développement social', name_en = 'Ministère de la famille solidarité égalité et développement social' WHERE id = '5ff69f01-a2be-4696-8681-15925b7943c7';
UPDATE public.partners SET name_fr = 'Entraide National', name_en = 'Entraide National' WHERE id = 'ebfc733e-24b6-4a20-ba3f-7e198b2a338a';
UPDATE public.partners SET name_fr = 'Conseil Provincial d''Esssaouira', name_en = 'Conseil Provincial d''Esssaouira' WHERE id = '7806ece3-401d-40a4-9764-af8a1db51ad9';
UPDATE public.partners SET name_fr = 'Conseil Régional de Marrakech Safi', name_en = 'Conseil Régional de Marrakech Safi' WHERE id = 'a977ce69-23e9-43e0-8979-6bd916015dfe';
UPDATE public.partners SET name_fr = 'Association d''appui au Complexe Social Ibtissama d''Essaouira', name_en = 'Association d''appui au Complexe Social Ibtissama d''Essaouira' WHERE id = '57197b30-fdc3-439e-984e-3421ec074fe1';
UPDATE public.partners SET name_fr = 'Association Essaouira Mogador', name_en = 'Association Essaouira Mogador' WHERE id = '3cc44ef7-d090-4c63-8dde-b668016d1d73';
UPDATE public.partners SET name_fr = 'Conseil Provincial du Tourisme d''Essaouira', name_en = 'Conseil Provincial du Tourisme d''Essaouira' WHERE id = 'a81593db-e5bc-4e9f-81fc-d38882348918';
UPDATE public.partners SET name_fr = 'Institut Francais d''Essaouira', name_en = 'Institut Francais d''Essaouira' WHERE id = '595ca93c-a584-49b3-b10d-143e41af3a15';
UPDATE public.partners SET name_fr = 'Association Sidi Bel Abasse Bab – Marrakech', name_en = 'Association Sidi Bel Abasse Bab – Marrakech' WHERE id = 'c8e7efb9-b363-40d1-bc16-db02dbed23e4';
UPDATE public.partners SET name_fr = 'Association Trait d''Union Marrakech', name_en = 'Association Trait d''Union Marrakech' WHERE id = '640f4fb4-f118-455e-a8ed-60b8d48f6e51';
UPDATE public.partners SET name_fr = 'Association village SOS – Ait Ourire (Marrakech)', name_en = 'Association village SOS – Ait Ourire (Marrakech)' WHERE id = '89e78a9f-b587-49c8-9a2b-244675163136';
UPDATE public.partners SET name_fr = 'Association Club Planche a Voile d''Essaouira', name_en = 'Association Club Planche a Voile d''Essaouira' WHERE id = 'dc9abe15-0eae-40c8-ac9b-c8af45585701';
UPDATE public.partners SET name_fr = 'Association La Danse des Femmes – France', name_en = 'Association La Danse des Femmes – France' WHERE id = 'de5473a3-fe9b-48fd-84c2-4e9c2c3e09b2';
UPDATE public.partners SET name_fr = 'Association Cap – Santé Belgique', name_en = 'Association Cap – Santé Belgique' WHERE id = '4da3df80-4692-43f9-aa71-09d72b345cec';
UPDATE public.partners SET name_fr = 'Hotel Golf Sofitel', name_en = 'Hotel Golf Sofitel' WHERE id = 'df697b90-b757-4d2c-bd6a-153af574d5d3';
UPDATE public.partners SET name_fr = 'Mr Hicham EL MEHRAB', name_en = 'Mr Hicham EL MEHRAB' WHERE id = 'd58fe8ee-39a0-4ee7-aca1-cfece740efbe';
UPDATE public.partners SET name_fr = 'Mr El Mahi BENBINE', name_en = 'Mr El Mahi BENBINE' WHERE id = '6d64a2bd-0dcc-4061-ac55-af9488d16648';
UPDATE public.partners SET name_fr = 'Docteur Naoufel EL MANSOURI', name_en = 'Docteur Naoufel EL MANSOURI' WHERE id = 'ae96681b-e6b7-42a9-93be-09921656fefd';
UPDATE public.partners SET name_fr = 'Mr Haj Brahim CHOUKRI', name_en = 'Mr Haj Brahim CHOUKRI' WHERE id = 'd44015fc-798a-433a-98aa-3396bb78fe01';
UPDATE public.partners SET name_fr = 'Mr Hassan NAJIB', name_en = 'Mr Hassan NAJIB' WHERE id = '25a8de67-77ab-4005-b750-298e0619d141';
UPDATE public.partners SET name_fr = 'Mme Soriya OTMANI', name_en = 'Mme Soriya OTMANI' WHERE id = '4ef83ed8-1f79-4d82-bbea-399bcb288d17';
UPDATE public.partners SET name_fr = 'Mr Mostafa OTMANI', name_en = 'Mr Mostafa OTMANI' WHERE id = 'c03aa25d-0be8-4028-9681-6a29e3296fa8';
UPDATE public.partners SET name_fr = 'Mr Noureddine OTMANI', name_en = 'Mr Noureddine OTMANI' WHERE id = '8b02c021-0e3e-4ad9-b44f-821f8a8e9e56';
UPDATE public.partners SET name_fr = 'Mr Hakim EL OUASSINI', name_en = 'Mr Hakim EL OUASSINI' WHERE id = '1d3b9cf9-93ea-49c3-bb85-705b2a5ddc61';
UPDATE public.partners SET name_fr = 'Mme Hannane EL OUASSINI', name_en = 'Mme Hannane EL OUASSINI' WHERE id = '6a6ddb53-b077-41a5-abf7-432a0ecfccd6';
UPDATE public.partners SET name_fr = 'Mr Patrique et Michel', name_en = 'Mr Patrique et Michel' WHERE id = 'cbf5b7f5-6728-4b62-87df-3bae2c9831b4';
UPDATE public.partners SET name_fr = 'Initiative Nationale pour le Développement Humain', name_en = 'National Initiative for Human Development' WHERE id = 'c3533f55-a068-4638-ac2f-db38f9cedc6a';
UPDATE public.partners SET name_fr = 'Ministère de la Solidarité et de l''Intégration', name_en = 'Ministry of Solidarity and Integration' WHERE id = 'e9e7f6ef-dacd-4ad3-9af4-c2b87ced5463';
UPDATE public.partners SET name_fr = 'Conseil Provincial d''Essaouira', name_en = 'Essaouira Provincial Council' WHERE id = '2e6e0fa1-b711-41d6-ad69-45e9eddc5ba8';
UPDATE public.partners SET name_fr = 'Direction Provinciale de la Santé', name_en = 'Provincial Health Directorate' WHERE id = '19604012-aeed-4366-a80b-c720b0e46ee0';
UPDATE public.partners SET name_fr = 'Académie de l''Éducation et de la Formation', name_en = 'Academy of Education and Training' WHERE id = 'bc3bbdd5-d725-47f0-8a18-01d3cf323ef5';
UPDATE public.partners SET name_fr = 'Entraide Nationale', name_en = 'National Cooperation' WHERE id = '70523397-a9f7-40f1-9c14-4890286cd092';
UPDATE public.partners SET name_fr = 'Bienfaiteurs et Entreprises Locales', name_en = 'Benefactors and Local Companies' WHERE id = 'ad868277-82d8-4ed4-a498-a40c9128753d';

-- News
UPDATE public.news SET title_fr = 'Visite de M. Mohammed Rachid à l''Institution Darna d''Essaouira', title_en = 'Visit of Mr. Mohammed Rachid to the Darna Institution in Essaouira', excerpt_fr = 'Le Gouverneur de la province d''Essaouira, M. Mohammed Rachid, a effectué une visite sur le terrain à l''Institution Darna, accompagné d''une délégation. Cette visite visait à observer de près...', excerpt_en = 'The Governor of the Essaouira province, Mr. Mohammed Rachid, made a field visit to the Darna Institution, accompanied by a delegation. This visit aimed to closely observe...' WHERE id = '13cb80f8-7e35-4311-bbad-759e33fe9a8d';
UPDATE public.news SET title_fr = 'Passage de l''Association Essaouira Darna dans l''émission ''Nass Lkhir'' sur 2M', title_en = 'Essaouira Darna Association featured on the ''Nass Lkhir'' show on 2M', excerpt_fr = 'L''Association Essaouira Darna a eu l''honneur d''accueillir l''équipe de l''émission sociale ''Nass Lkhir'' diffusée sur la chaîne 2M. Ce reportage met en lumière les initiatives...', excerpt_en = 'The Essaouira Darna Association had the honor of welcoming the team of the social program ''Nass Lkhir'' broadcast on the 2M channel. This report highlights the initiatives...' WHERE id = '9399b496-778a-4dda-a869-85f77563b288';
UPDATE public.news SET title_fr = 'Célébration de la Journée Nationale de l''Orphelin 2021', title_en = 'Celebration of the National Orphan Day 2021', excerpt_fr = 'À l''occasion de la Journée Nationale de l''Orphelin, l''association organise une campagne de collecte de dons auprès des bienfaiteurs et amis de l''association pour redonner le sourire aux enfants...', excerpt_en = 'On the occasion of the National Orphan Day, the association is organizing a fundraising campaign with benefactors and friends of the association to bring smiles back to the children...' WHERE id = '8ac85a90-c753-45a4-a19b-4fdf5d1ea444';
UPDATE public.news SET title_fr = 'Célébration de la Journée Nationale de l''Orphelin 2021', title_en = 'Celebration of the National Orphan Day 2021', excerpt_fr = 'À l''occasion de la Journée Nationale de l''Orphelin, l''association organise une campagne de collecte de dons auprès des bienfaiteurs et amis de l''association pour redonner le sourire aux enfants...', excerpt_en = 'On the occasion of the National Orphan Day, the association is organizing a fundraising campaign with benefactors and friends of the association to bring smiles back to the children...' WHERE id = 'cb1c62f4-bff6-4867-9738-42405ab7013d';
UPDATE public.news SET title_fr = 'Passage de l''Association Essaouira Darna dans l''émission ''Nass Lkhir'' sur 2M', title_en = 'Essaouira Darna Association featured on the ''Nass Lkhir'' show on 2M', excerpt_fr = 'L''Association Essaouira Darna a eu l''honneur d''accueillir l''équipe de l''émission sociale ''Nass Lkhir'' diffusée sur la chaîne 2M. Ce reportage met en lumière les initiatives...', excerpt_en = 'The Essaouira Darna Association had the honor of welcoming the team of the social program ''Nass Lkhir'' broadcast on the 2M channel. This report highlights the initiatives...' WHERE id = '2b78e12b-853d-402d-9627-0795b67f494b';
UPDATE public.news SET title_fr = 'Visite de M. Mohammed Rachid à l''Institution Darna d''Essaouira', title_en = 'Visit of Mr. Mohammed Rachid to the Darna Institution in Essaouira', excerpt_fr = 'Le Gouverneur de la province d''Essaouira, M. Mohammed Rachid, a effectué une visite sur le terrain à l''Institution Darna, accompagné d''une délégation. Cette visite visait à observer de près...', excerpt_en = 'The Governor of the Essaouira province, Mr. Mohammed Rachid, made a field visit to the Darna Institution, accompanied by a delegation. This visit aimed to closely observe...' WHERE id = 'bd1e16f2-9c51-4e77-902e-4b88ab3be51d';
UPDATE public.news SET title_fr = 'يصصصصصصصصصصص', title_en = 'يصصصصصصصصصصص', excerpt_fr = 'لققققققققققققققققققققققققق', excerpt_en = 'لققققققققققققققققققققققققق' WHERE id = 'c5ed0536-381b-488c-bcf7-29911c88ede1';
